theme: jekyll-theme-minimal
title: Namrata Nadagouda
logo: /images/SquarePic_20200608_09515661_2.jpg
description: PhD student, School of ECE, GaTech
email:namrata.nadagouda@gatech.edu
show_downloads: false
